name: Clippy

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  FEATURES: xq-audio,discord-presence,log,debug-views,pu-checks,gdb-server,dldi
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  clippy:
    name: Clippy (${{ matrix.os }})
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install nightly toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
          toolchain: nightly
          components: clippy

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: cargo-registry
        enableCrossOsArchive: true

    - name: Install ALSA
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev

    - name: Update dependencies
      run: cargo update

    - name: Run clippy (no default features)
      uses: actions-rs/clippy-check@v1
      with:
        name: Run clippy (${{ matrix.os }}, no default features)
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --no-default-features --package dust-desktop

    - name: Run clippy (all features)
      uses: actions-rs/clippy-check@v1
      with:
        name: Run clippy (${{ matrix.os }}, all features)
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --no-default-features --features=${{ env.FEATURES }} --package dust-desktop
